
#pragma once


#define OAK_MEMORY_ALLOCATOR_NEDPOOLING     1
#define OAK_MEMORY_ALLOCATOR_NED            2
#define OAK_MEMORY_ALLOCATOR_STD            3

#define OAK_MEMORY_ALLOCATOR OAK_MEMORY_ALLOCATOR_NEDPOOLING
//#define OAK_MEMORY_ALLOCATOR OAK_MEMORY_ALLOCATOR_NED
//#define OAK_MEMORY_ALLOCATOR OAK_MEMORY_ALLOCATOR_STD

#define OAK_SIMD_ALIGNMENT 128
#define OAK_MEMORY_TRACKER 0

